// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type OrderHistory struct {
	ent.Schema
}

func (OrderHistory) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("order_id"), field.String("user_id").Optional(), field.String("address_id").Optional(), field.Time("ordered_at"), field.Int32("user_order_number"), field.String("order_status"), field.Int32("order_total_price"), field.String("payment_method"), field.String("payment_status"), field.String("payment_info").Optional(), field.String("payment_key")}
}
func (OrderHistory) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("order_histories").Unique().Field("user_id"), edge.From("user_addre", UserAddress.Type).Ref("order_histories").Unique().Field("address_id"), edge.To("order_rows", OrderRow.Type)}
}
func (OrderHistory) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "order_history"}}
}
