// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type OrderRow struct {
	ent.Schema
}

func (OrderRow) Fields() []ent.Field {
	return []ent.Field{field.Int32("id").StorageKey("order_row_id"), field.String("order_id").Optional(), field.Int32("sku").Optional(), field.String("size"), field.Int32("quantity"), field.String("delivery_status"), field.String("delivery_company").Optional(), field.String("delivery_number").Optional()}
}
func (OrderRow) Edges() []ent.Edge {
	return []ent.Edge{edge.From("order_history", OrderHistory.Type).Ref("order_rows").Unique().Field("order_id"), edge.From("product_info", ProductInfo.Type).Ref("order_rows").Unique().Field("sku")}
}
func (OrderRow) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "order_row"}}
}
