// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type UserAddress struct {
	ent.Schema
}

func (UserAddress) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("address_id"), field.String("user_id").Optional(), field.String("kr_name"), field.String("en_name"), field.String("custom_id"), field.String("phone"), field.String("kr_address"), field.String("kr_address_detail"), field.String("en_address"), field.String("en_address_detail"), field.Bool("permanent")}
}
func (UserAddress) Edges() []ent.Edge {
	return []ent.Edge{edge.To("order_histories", OrderHistory.Type), edge.From("user", User.Type).Ref("user_address").Unique().Field("user_id")}
}
func (UserAddress) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user_address"}}
}
