// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("user_id"), field.String("email").Optional().Unique(), field.String("password").Optional(), field.String("kr_name"), field.Time("register_at"), field.Time("last_login"), field.String("sign_up_type")}
}
func (User) Edges() []ent.Edge {
	return []ent.Edge{edge.To("order_histories", OrderHistory.Type), edge.To("user_address", UserAddress.Type)}
}
func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user"}}
}
