import { ProductProps } from '@/utils/hooks/data/type'

const productMock: ProductProps[] = [
    {
        sku: 14,
        brand: 'adidas originals',
        productName: 'bermuda sneaker college burgundy',
        productId: 'IE7426',
        shippingFee: 19000,
        price: 178000,
        intl: true,
        color: 'COLLEGE BURGUNDY/CREAM WHITE/MAROON',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '버뮤다 컬리지 버건디',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 15,
        brand: 'adidas originals',
        productName: 'bermuda sneaker college purple cream white',
        productId: 'IE7427',
        shippingFee: 19000,
        price: 159000,
        intl: true,
        color: 'COLLEGE PURPLE/CREAM WHITE/DARK PURPLE',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '버뮤다 컬리지 퍼플 크림 화이트',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 16,
        brand: 'our legacy',
        productName: '(W) cardigan mole grey mohair',
        productId: 'W4236CM',
        shippingFee: 15000,
        price: 599000,
        intl: true,
        color: 'MOLE GREY',
        category: '의류',
        categorySpec: '가디건',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '(W) 가디건 몰 그레이 모헤어',
        korBrand: '아워레거시',
    },
    {
        sku: 17,
        brand: 'patagonia',
        productName: 'microdini hooded fleece tidepool blue',
        productId: '26210-TIDB',
        shippingFee: 15000,
        price: 198000,
        intl: true,
        color: 'TIDEPOOL BLUE',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '후드 플리스 타이드풀 블루',
        korBrand: '파타고니아',
    },
    {
        sku: 18,
        brand: 'adidas originals',
        productName: 'adimatic panton crystal white',
        productId: 'HQ6901',
        shippingFee: 19000,
        price: 109000,
        intl: true,
        color: 'PHANTONE/CRYSTAL WHITE',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '아디매틱 팬톤 크리스탈 화이트',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 19,
        brand: 'clarks originals',
        productName: 'coal london black suede',
        productId: '26171744',
        shippingFee: 19000,
        price: 189000,
        intl: true,
        color: 'BLACK/SUEDE',
        category: '신발',
        categorySpec: '단화',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '콜 런던 블랙 스웨이드',
        korBrand: '클락스',
    },
    {
        sku: 20,
        brand: 'clarks originals',
        productName: 'coal london maple suede',
        productId: '26171491',
        shippingFee: 19000,
        price: 189000,
        intl: true,
        color: 'MAPLE/SUEDE',
        category: '신발',
        categorySpec: '단화',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '콜 런던 메이플 스웨이드',
        korBrand: '클락스',
    },
    {
        sku: 21,
        brand: 'clarks originals',
        productName: 'wallabee boot black suede',
        productId: '26155517',
        shippingFee: 19000,
        price: 199000,
        intl: true,
        color: 'BLACK/SUEDE',
        category: '신발',
        categorySpec: '단화',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '왈라비 부츠 블랙 스웨이드',
        korBrand: '클락스',
    },
    {
        sku: 22,
        brand: 'adidas originals',
        productName: 'gazelle bold core black cloud white cloud white',
        productId: 'IE0876',
        shippingFee: 19000,
        price: 159000,
        intl: true,
        color: 'CORE BLACK/CLOUD WHITE',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '가젤 볼드 코어 블랙 클라우드 화이트',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 23,
        brand: 'adidas originals',
        productName: 'gazelle indoor semi green spark almost yellow cream white',
        productId: 'IE2948',
        shippingFee: 19000,
        price: 159000,
        intl: true,
        color: 'GREEN SPARK/CREAM WHITE',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '가젤 인도어 세미 그린 스파크 크림 화이트',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 24,
        brand: 'adidas originals',
        productName: 'gazelle indoor wonder clay clear pink gum',
        productId: 'IE2946',
        shippingFee: 19000,
        price: 171000,
        intl: true,
        color: 'WONDER CLAY/CLEAR PINK',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '가젤 인도어 원더 클레이 클리어 핑크',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 25,
        brand: 'adidas originals',
        productName: 'samba og shadow olive preloved green gum',
        productId: 'IG6175',
        shippingFee: 19000,
        price: 179000,
        intl: true,
        color: 'HADOW OLIVE/PRELOVED GREEN',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '삼바 og 쉐도우 올리브 그린 검',
        korBrand: '아디다스 오리지널스',
    },
    {
        sku: 26,
        brand: 'patagonia',
        productName: "women's microdini fleece pullover obsidian plum",
        productId: '26260-OBPL',
        shippingFee: 15000,
        price: 191000,
        intl: true,
        color: 'OBSIDIAN PLUM',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '여성 플리스 옵시디언 플럼',
        korBrand: '파타고니아',
    },
    {
        sku: 27,
        brand: 'patagonia',
        productName: 'patagonia funhoggers anorak pullover jacket classic',
        productId: '20325-CSC',
        shippingFee: 15000,
        price: 199000,
        intl: true,
        color: 'FUNHOGGERS',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '펀호거스 플리스 코튼 아노락 클래식 탄',
        korBrand: '파타고니아',
    },
    {
        sku: 28,
        brand: 'patagonia',
        productName: 'microdini fleece pullover plume grey',
        productId: '26200-PLGY',
        shippingFee: 15000,
        price: 180000,
        intl: true,
        color: 'PLUME GREY',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '후드 플리스 플룸 그레이',
        korBrand: '파타고니아',
    },
    {
        sku: 29,
        brand: 'patagonia',
        productName: 'microdini hooded fleece pitch blue',
        productId: '26210-PIBL',
        shippingFee: 15000,
        price: 195000,
        intl: true,
        color: 'PITCH BLUE',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '후드 플리스 피치 블루',
        korBrand: '파타고니아',
    },
    {
        sku: 30,
        brand: 'patagonia',
        productName: 'retro pile fleece jacket el cap khaki',
        productId: '22801-ELKH',
        shippingFee: 15000,
        price: 229000,
        intl: true,
        color: 'KHAKI',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '레트로 파일 플리스 자켓 엘 캡 카키',
        korBrand: '파타고니아',
    },
    {
        sku: 100,
        brand: "arc'teryx",
        productName: 'beta jacket black sapphire',
        productId: 'X000006876',
        shippingFee: 15000,
        price: 838000,
        intl: true,
        color: 'BLACK SAPPHIRE',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '베타 자켓 블랙 사파이어',
        korBrand: '아크테릭스',
    },
    {
        sku: 101,
        brand: "arc'teryx",
        productName: 'gamma hoodie jacket black sapphire',
        productId: 'X000007465',
        shippingFee: 15000,
        price: 585000,
        intl: true,
        color: 'BLACK SAPPHIRE',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '감마 자켓 블랙 사파이어',
        korBrand: '아크테릭스',
    },
    {
        sku: 102,
        brand: "arc'teryx",
        productName: "captive arc'word long sleeve t shirt arctic silk",
        productId: 'X000006544',
        shippingFee: 15000,
        price: 140000,
        intl: true,
        color: 'ARCTIC SILK',
        category: '의류',
        categorySpec: '긴팔 티셔츠',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '캡티브 아크우드 롱 슬리브 셔츠 아크틱 실크',
        korBrand: '아크테릭스',
    },
    {
        sku: 103,
        brand: "arc'teryx",
        productName: 'thorium hoodie black',
        productId: 'X000007380',
        shippingFee: 15000,
        price: 835000,
        intl: true,
        color: 'BLACK',
        category: '의류',
        categorySpec: '패딩',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '토륨 후디 블랙',
        korBrand: '아크테릭스',
    },
    {
        sku: 104,
        brand: "arc'teryx",
        productName: 'atom hoodie black sapphire',
        productId: 'X000007487',
        shippingFee: 15000,
        price: 585000,
        intl: true,
        color: ' BLACK SAPPHIRE',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '아톰 후디 블랙 사파이어',
        korBrand: '아크테릭스',
    },
    {
        sku: 105,
        brand: "arc'teryx",
        productName: 'atom vest black',
        productId: 'X000007475',
        shippingFee: 15000,
        price: 440000,
        intl: true,
        color: 'BLACK',
        category: '의류',
        categorySpec: '베스트',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '아톰 베스트 블랙',
        korBrand: '아크테릭스',
    },
    {
        sku: 106,
        brand: "arc'teryx",
        productName: 'cerium hooded jacket black',
        productId: 'X000007313',
        shippingFee: 15000,
        price: 785000,
        intl: true,
        color: 'BLACK',
        category: '의류',
        categorySpec: '숏패딩',
        imgType: 'webp',
        size: [],
        deploy: 0,
        korProductName: '세륨 후디 블랙',
        korBrand: '아크테릭스',
    },
    {
        sku: 107,
        brand: "arc'teryx",
        productName: 'atom hoodie smoke bluff',
        productId: 'X000007487S',
        shippingFee: 15000,
        price: 485000,
        intl: true,
        color: ' SMOKE BLUFF',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '아톰 후디 스모크 블러프',
        korBrand: '아크테릭스',
    },
    {
        sku: 108,
        brand: "arc'teryx",
        productName: 'squamish hoodie smoke bluff',
        productId: 'X000007411S',
        shippingFee: 15000,
        price: 225000,
        intl: true,
        color: '/',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: ' 스쿼미시 후디 스모크 블러프',
        korBrand: '아크테릭스',
    },
    {
        sku: 109,
        brand: 'the north face',
        productName: 'transverse dryvent jacket tnf black',
        productId: 'NF0A852EJK3',
        shippingFee: 15000,
        price: 530000,
        intl: true,
        color: '\bBLACK',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '트랜스버스 드라이벤트 자켓 블랙',
        korBrand: '노스페이스',
    },
    {
        sku: 111,
        brand: 'the north face',
        productName: 'matterhorn face long sleeve t shirt gardenia white',
        productId: 'NF0A854BN3N',
        shippingFee: 15000,
        price: 70000,
        intl: true,
        color: 'GARDENIA WHITE',
        category: '의류',
        categorySpec: '긴팔 티셔츠',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '마테호른 페이스 롱 슬리브 가드니아 화이트',
        korBrand: '노스페이스',
    },
    {
        sku: 112,
        brand: 'the north face',
        productName: 'ampato quilted liner jacket sulphur moss',
        productId: 'NF0A852AI0N',
        shippingFee: 15000,
        price: 200000,
        intl: true,
        color: 'SULPHUR MOSS',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '앰파토 퀼티드 리니어 자켓 설퍼스 모스',
        korBrand: '노스페이스',
    },
    {
        sku: 113,
        brand: 'the north face',
        productName: '1996 retro nuptse jacket pine needle/summit navy',
        productId: 'NF0A3C8DOAS',
        shippingFee: 15000,
        price: 535000,
        intl: true,
        color: 'PINE NEEDLE/SUMMIT NAVY',
        category: '의류',
        categorySpec: '숏패딩',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '1996 레트로 자켓 파인 니들 서밋 네이비',
        korBrand: '노스페이스',
    },
    {
        sku: 114,
        brand: 'the north face',
        productName: 'extreme pile full zip jacket misty sage fallen leaves',
        productId: 'NF0A7URLOPH',
        shippingFee: 15000,
        price: 230000,
        intl: true,
        color: 'MISTY SAGE FALLEN LEAVES',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '익스트림 파일 풀 집 자켓 미스티 세이지 폴른 리브스',
        korBrand: '노스페이스',
    },
    {
        sku: 115,
        brand: 'the north face',
        productName: 'extreme pile pullover jacket gardenia white/sulphur moss',
        productId: 'NF0A7URNN5I',
        shippingFee: 15000,
        price: 150000,
        intl: true,
        color: 'GARDENIA WHITE/SULPHUR MOSS',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '익스트림 파일 풀오버 자켓 가드니아 화이트 서퍼 모스',
        korBrand: '노스페이스',
    },
    {
        sku: 116,
        brand: 'the north face',
        productName: 'ampato quilted liner jacket tnf black',
        productId: 'NF0A852AJK3',
        shippingFee: 15000,
        price: 200000,
        intl: true,
        color: 'TNF BLACK',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '앰파토 퀼티드 리니어 자켓 블랙',
        korBrand: '노스페이스',
    },
    {
        sku: 117,
        brand: 'the north face',
        productName: 'denali jacket tnf black',
        productId: 'NF0A7UQ8JK3',
        shippingFee: 15000,
        price: 370000,
        intl: true,
        color: 'BLACK',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '드네일 자켓 블랙',
        korBrand: '노스페이스',
    },
    {
        sku: 118,
        brand: 'the north face',
        productName: '1996 retro nuptse jacket boysenberry tnf black',
        productId: 'NF0A3C8DKK9',
        shippingFee: 15000,
        price: 545000,
        intl: true,
        color: 'BOYSENBERRY/TNF BLACK',
        category: '의류',
        categorySpec: '패딩',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '1996 레트로 자켓 보이젠 베리 블랙',
        korBrand: '노스페이스',
    },
    {
        sku: 120,
        brand: 'patagonia',
        productName: 'fitz roy icon uprisal hoodie gravel heather',
        productId: '39666',
        shippingFee: 15000,
        price: 153000,
        intl: true,
        color: ' GRAVEL HEATHER',
        category: '의류',
        categorySpec: '후드',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '피츠 로이 아이콘 후드 그레이벌 헤더',
        korBrand: '파타고니아',
    },
    {
        sku: 121,
        brand: 'patagonia',
        productName: 'retro pile vest el cap khaki',
        productId: '22821-KHA',
        shippingFee: 15000,
        price: 210000,
        intl: true,
        color: 'KHAKI',
        category: '의류',
        categorySpec: '베스트',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '레트로 파일 엘 캡 카키',
        korBrand: '파타고니아',
    },
    {
        sku: 122,
        brand: 'the north face',
        productName: 'platte sherpa 1/4 zip fleece khaki stone',
        productId: 'NF0A5GFJLK5',
        shippingFee: 15000,
        price: 229000,
        intl: true,
        color: 'KHAKI STONE',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '플랫 쉐르파 집 플리스 카키 스톤',
        korBrand: '노스페이스',
    },
    {
        sku: 123,
        brand: 'the north face',
        productName: 'printed campshire fleece hoodie sulphur moss mountain geo print',
        productId: 'NF0A84HXOVH',
        shippingFee: 15000,
        price: 242000,
        intl: true,
        color: 'SULPHUR MOSS/MOUNTAIN GEO PRINT',
        category: '의류',
        categorySpec: '후리스',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '프린티드 캠프샤이어 플리스 후디 서퍼 모스 마운틴 지오 프린트',
        korBrand: '노스페이스',
    },
    {
        sku: 124,
        brand: 'the north face',
        productName: 'panel cap almond butter',
        productId: 'NF0A3SH3I0J',
        shippingFee: 15000,
        price: 56000,
        intl: true,
        color: 'ALMOND BUTTER',
        category: '기타',
        categorySpec: '모자',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '패널 캡 아몬드 버터',
        korBrand: '노스페이스',
    },
    {
        sku: 125,
        brand: 'patagonia',
        productName: 'retro pile jacket nouveau green',
        productId: '22801X',
        shippingFee: 15000,
        price: 209000,
        intl: true,
        color: ' NOUVEAU GREEN',
        category: '의류',
        categorySpec: '자켓',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '레트로 파일 누브 그린',
        korBrand: '파타고니아',
    },
    {
        sku: 126,
        brand: 'new balance',
        productName: 'MT580 workwear honeycomb raw cashew',
        productId: 'MT580AB2',
        shippingFee: 19000,
        price: 111000,
        intl: true,
        color: 'WORKWEAR/HONEYCOMB/RAW CASHEW',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: 'mt580 워크웨어 허니콤 로 캐슈',
        korBrand: '뉴발란스',
    },
    {
        sku: 127,
        brand: 'new balance',
        productName: 'OU576 shoes eden alloy grey violet',
        productId: 'OU576GGK',
        shippingFee: 19000,
        price: 240000,
        intl: true,
        color: 'EDEN',
        category: '신발',
        categorySpec: '스니커즈',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '576 메이드 인 UK 에덴',
        korBrand: '뉴발란스',
    },
    {
        sku: 128,
        brand: 'new balance',
        productName: 'M991 shoes sequoia falcon',
        productId: 'M991PTY',
        shippingFee: 19000,
        price: 240000,
        intl: true,
        color: 'SEQUOIA/FALCON',
        category: '신발',
        categorySpec: '운동화',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '991 메이드 인 UK 세퀘이아 팔콘',
        korBrand: '뉴발란스',
    },
    {
        sku: 129,
        brand: 'new balance',
        productName: 'MT580 black teal',
        productId: 'MT580VE2',
        shippingFee: 19000,
        price: 155000,
        intl: true,
        color: 'BLACK/TEAL',
        category: '신발',
        categorySpec: '운동화',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: 'MT580 블랙 틸',
        korBrand: '뉴발란스',
    },
    {
        sku: 131,
        brand: 'adidas originals',
        productName: 'hyperturf shoes earth strata core black collegiate green',
        productId: 'HQ6606',
        shippingFee: 19000,
        price: 112000,
        intl: true,
        color: 'EARTH STRATA/CORE BLACK/COLLEGIATE GREEN',
        category: '신발',
        categorySpec: '운동화',
        imgType: 'webp',
        size: [],
        deploy: 1,
        korProductName: '하이퍼서프 코어 블랙 콜리게이트 그린',
        korBrand: '아디다스 오리지널스',
    },
]

export default productMock
