// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OrderHistory is the predicate function for orderhistory builders.
type OrderHistory func(*sql.Selector)

// OrderRow is the predicate function for orderrow builders.
type OrderRow func(*sql.Selector)

// ProductInfo is the predicate function for productinfo builders.
type ProductInfo func(*sql.Selector)

// Size is the predicate function for size builders.
type Size func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAddress is the predicate function for useraddress builders.
type UserAddress func(*sql.Selector)
