export const brandIndex = {
    A: ['acne studios', 'adidas originals', 'ami', 'a.p.c', "arc'teryx", 'asics'],
    B: ['Barbour'],
    C: ['c.p. company', 'clarks originals', 'comme des garcons'],
    H: ['human made'],
    K: ['keen'],
    M: ['maison kitsune'],
    N: ['needles', 'new balance', 'nike'],
    O: ['our legacy'],
    P: ['patagonia', 'polo', 'porter'],
    S: ['salomon', 'stone island'],
    T: ['the north face'],
    V: ['vans', 'vivienne westwood'],
}

export const defaultSize = {
    의류: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    신발: [
        '220',
        '225',
        '230',
        '235',
        '240',
        '245',
        '250',
        '255',
        '260',
        '265',
        '270',
        '275',
        '280',
        '285',
        '290',
        '295',
        '300',
    ],
    기타: ['One Size'],
}

export const productCategory = {
    의류: [
        '가디건',
        '베스트',
        '긴팔 티셔츠',
        '니트',
        '반팔 티셔츠',
        '셔츠',
        '스웨터',
        '패딩',
        '롱패딩',
        '숏패딩',
        '자켓',
        '후드',
        '바지',
        '반바지',
        '후리스',
    ],
    신발: ['스니커즈', '단화', '장화', '운동화'],
    기타: ['악세서리', '지갑', '모자', '가방', '기타'],
    전체: [
        '가디건',
        '긴팔 티셔츠',
        '니트',
        '반팔 티셔츠',
        '셔츠',
        '스웨터',
        '패딩',
        '후드',
        '바지',
        '반바지',
        '악세서리',
        '지갑',
        '모자',
        '가방',
        '기타',
        '스니커즈',
        '단화',
        '장화',
        '운동화',
    ],
}
export const productSize = {
    의류: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    신발: [
        '220',
        '225',
        '230',
        '235',
        '240',
        '245',
        '250',
        '255',
        '260',
        '265',
        '270',
        '275',
        '280',
        '285',
        '290',
        '295',
        '300',
    ],
    기타: ['ONE SIZE'],
    전체: [
        '220',
        '225',
        '230',
        '235',
        '240',
        '245',
        '250',
        '255',
        '260',
        '265',
        '270',
        '275',
        '280',
        '285',
        '290',
        '295',
        '300',
        'XS',
        'S',
        'M',
        'L',
        'XL',
        'XXL',
        'XXXL',
        'one size',
    ],
}

export const brandArr = [
    'acne studios',
    'adidas originals',
    'ami',
    'a.p.c.',
    "arc'teryx",
    'asics',
    'barbour',
    'c.p. company',
    'clarks originals',
    'comme des garcons',
    'human made',
    'keen',
    'maison kitsune',
    'needles',
    'new balance',
    'nike',
    'our legacy',
    'patagonia',
    'polo',
    'porter',
    'salomon',
    'stone island',
    'the north face',
    'vans',
    'vivienne westwood',
]

export const filterMetaData = {
    정렬순: ['최신순', '낮은 가격 순', '높은 가격 순'],
    브랜드: brandArr,
    종류: productCategory,
    사이즈: productSize,
    배송: ['해외배송', '국내배송'],
    가격: [0, 1000000],
}
