// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"product-server/ent/orderrow"
	"product-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderRowDelete is the builder for deleting a OrderRow entity.
type OrderRowDelete struct {
	config
	hooks    []Hook
	mutation *OrderRowMutation
}

// Where appends a list predicates to the OrderRowDelete builder.
func (ord *OrderRowDelete) Where(ps ...predicate.OrderRow) *OrderRowDelete {
	ord.mutation.Where(ps...)
	return ord
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ord *OrderRowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ord.sqlExec, ord.mutation, ord.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ord *OrderRowDelete) ExecX(ctx context.Context) int {
	n, err := ord.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ord *OrderRowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderrow.Table, sqlgraph.NewFieldSpec(orderrow.FieldID, field.TypeInt32))
	if ps := ord.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ord.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ord.mutation.done = true
	return affected, err
}

// OrderRowDeleteOne is the builder for deleting a single OrderRow entity.
type OrderRowDeleteOne struct {
	ord *OrderRowDelete
}

// Where appends a list predicates to the OrderRowDelete builder.
func (ordo *OrderRowDeleteOne) Where(ps ...predicate.OrderRow) *OrderRowDeleteOne {
	ordo.ord.mutation.Where(ps...)
	return ordo
}

// Exec executes the deletion query.
func (ordo *OrderRowDeleteOne) Exec(ctx context.Context) error {
	n, err := ordo.ord.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderrow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ordo *OrderRowDeleteOne) ExecX(ctx context.Context) {
	if err := ordo.Exec(ctx); err != nil {
		panic(err)
	}
}
