// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"product-server/ent/predicate"
	"product-server/ent/productinfo"
	"product-server/ent/size"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SizeQuery is the builder for querying Size entities.
type SizeQuery struct {
	config
	ctx             *QueryContext
	order           []size.OrderOption
	inters          []Interceptor
	predicates      []predicate.Size
	withProductInfo *ProductInfoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SizeQuery builder.
func (sq *SizeQuery) Where(ps ...predicate.Size) *SizeQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SizeQuery) Limit(limit int) *SizeQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SizeQuery) Offset(offset int) *SizeQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SizeQuery) Unique(unique bool) *SizeQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SizeQuery) Order(o ...size.OrderOption) *SizeQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryProductInfo chains the current query on the "product_info" edge.
func (sq *SizeQuery) QueryProductInfo() *ProductInfoQuery {
	query := (&ProductInfoClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(size.Table, size.FieldID, selector),
			sqlgraph.To(productinfo.Table, productinfo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, size.ProductInfoTable, size.ProductInfoColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Size entity from the query.
// Returns a *NotFoundError when no Size was found.
func (sq *SizeQuery) First(ctx context.Context) (*Size, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{size.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SizeQuery) FirstX(ctx context.Context) *Size {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Size ID from the query.
// Returns a *NotFoundError when no Size ID was found.
func (sq *SizeQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{size.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SizeQuery) FirstIDX(ctx context.Context) int32 {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Size entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Size entity is found.
// Returns a *NotFoundError when no Size entities are found.
func (sq *SizeQuery) Only(ctx context.Context) (*Size, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{size.Label}
	default:
		return nil, &NotSingularError{size.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SizeQuery) OnlyX(ctx context.Context) *Size {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Size ID in the query.
// Returns a *NotSingularError when more than one Size ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SizeQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{size.Label}
	default:
		err = &NotSingularError{size.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SizeQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Sizes.
func (sq *SizeQuery) All(ctx context.Context) ([]*Size, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Size, *SizeQuery]()
	return withInterceptors[[]*Size](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SizeQuery) AllX(ctx context.Context) []*Size {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Size IDs.
func (sq *SizeQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err = sq.Select(size.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SizeQuery) IDsX(ctx context.Context) []int32 {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SizeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SizeQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SizeQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SizeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SizeQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SizeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SizeQuery) Clone() *SizeQuery {
	if sq == nil {
		return nil
	}
	return &SizeQuery{
		config:          sq.config,
		ctx:             sq.ctx.Clone(),
		order:           append([]size.OrderOption{}, sq.order...),
		inters:          append([]Interceptor{}, sq.inters...),
		predicates:      append([]predicate.Size{}, sq.predicates...),
		withProductInfo: sq.withProductInfo.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithProductInfo tells the query-builder to eager-load the nodes that are connected to
// the "product_info" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SizeQuery) WithProductInfo(opts ...func(*ProductInfoQuery)) *SizeQuery {
	query := (&ProductInfoClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withProductInfo = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sku int32 `json:"sku,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Size.Query().
//		GroupBy(size.FieldSku).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SizeQuery) GroupBy(field string, fields ...string) *SizeGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SizeGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = size.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sku int32 `json:"sku,omitempty"`
//	}
//
//	client.Size.Query().
//		Select(size.FieldSku).
//		Scan(ctx, &v)
func (sq *SizeQuery) Select(fields ...string) *SizeSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SizeSelect{SizeQuery: sq}
	sbuild.label = size.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SizeSelect configured with the given aggregations.
func (sq *SizeQuery) Aggregate(fns ...AggregateFunc) *SizeSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SizeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !size.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SizeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Size, error) {
	var (
		nodes       = []*Size{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withProductInfo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Size).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Size{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withProductInfo; query != nil {
		if err := sq.loadProductInfo(ctx, query, nodes, nil,
			func(n *Size, e *ProductInfo) { n.Edges.ProductInfo = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SizeQuery) loadProductInfo(ctx context.Context, query *ProductInfoQuery, nodes []*Size, init func(*Size), assign func(*Size, *ProductInfo)) error {
	ids := make([]int32, 0, len(nodes))
	nodeids := make(map[int32][]*Size)
	for i := range nodes {
		fk := nodes[i].Sku
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(productinfo.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sku" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *SizeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SizeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(size.Table, size.Columns, sqlgraph.NewFieldSpec(size.FieldID, field.TypeInt32))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, size.FieldID)
		for i := range fields {
			if fields[i] != size.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sq.withProductInfo != nil {
			_spec.Node.AddColumnOnce(size.FieldSku)
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SizeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(size.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = size.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SizeGroupBy is the group-by builder for Size entities.
type SizeGroupBy struct {
	selector
	build *SizeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SizeGroupBy) Aggregate(fns ...AggregateFunc) *SizeGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SizeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SizeQuery, *SizeGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SizeGroupBy) sqlScan(ctx context.Context, root *SizeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SizeSelect is the builder for selecting fields of Size entities.
type SizeSelect struct {
	*SizeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SizeSelect) Aggregate(fns ...AggregateFunc) *SizeSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SizeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SizeQuery, *SizeSelect](ctx, ss.SizeQuery, ss, ss.inters, v)
}

func (ss *SizeSelect) sqlScan(ctx context.Context, root *SizeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
