// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"product-server/ent/orderhistory"
	"product-server/ent/predicate"
	"product-server/ent/user"
	"product-server/ent/useraddress"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetEmail sets the "email" field.
func (uu *UserUpdate) SetEmail(s string) *UserUpdate {
	uu.mutation.SetEmail(s)
	return uu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uu *UserUpdate) SetNillableEmail(s *string) *UserUpdate {
	if s != nil {
		uu.SetEmail(*s)
	}
	return uu
}

// ClearEmail clears the value of the "email" field.
func (uu *UserUpdate) ClearEmail() *UserUpdate {
	uu.mutation.ClearEmail()
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetPassword(*s)
	}
	return uu
}

// ClearPassword clears the value of the "password" field.
func (uu *UserUpdate) ClearPassword() *UserUpdate {
	uu.mutation.ClearPassword()
	return uu
}

// SetKrName sets the "kr_name" field.
func (uu *UserUpdate) SetKrName(s string) *UserUpdate {
	uu.mutation.SetKrName(s)
	return uu
}

// SetNillableKrName sets the "kr_name" field if the given value is not nil.
func (uu *UserUpdate) SetNillableKrName(s *string) *UserUpdate {
	if s != nil {
		uu.SetKrName(*s)
	}
	return uu
}

// SetRegisterAt sets the "register_at" field.
func (uu *UserUpdate) SetRegisterAt(t time.Time) *UserUpdate {
	uu.mutation.SetRegisterAt(t)
	return uu
}

// SetNillableRegisterAt sets the "register_at" field if the given value is not nil.
func (uu *UserUpdate) SetNillableRegisterAt(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetRegisterAt(*t)
	}
	return uu
}

// SetLastLogin sets the "last_login" field.
func (uu *UserUpdate) SetLastLogin(t time.Time) *UserUpdate {
	uu.mutation.SetLastLogin(t)
	return uu
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (uu *UserUpdate) SetNillableLastLogin(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetLastLogin(*t)
	}
	return uu
}

// SetSignUpType sets the "sign_up_type" field.
func (uu *UserUpdate) SetSignUpType(s string) *UserUpdate {
	uu.mutation.SetSignUpType(s)
	return uu
}

// SetNillableSignUpType sets the "sign_up_type" field if the given value is not nil.
func (uu *UserUpdate) SetNillableSignUpType(s *string) *UserUpdate {
	if s != nil {
		uu.SetSignUpType(*s)
	}
	return uu
}

// AddOrderHistoryIDs adds the "order_histories" edge to the OrderHistory entity by IDs.
func (uu *UserUpdate) AddOrderHistoryIDs(ids ...string) *UserUpdate {
	uu.mutation.AddOrderHistoryIDs(ids...)
	return uu
}

// AddOrderHistories adds the "order_histories" edges to the OrderHistory entity.
func (uu *UserUpdate) AddOrderHistories(o ...*OrderHistory) *UserUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uu.AddOrderHistoryIDs(ids...)
}

// AddUserAddresIDs adds the "user_address" edge to the UserAddress entity by IDs.
func (uu *UserUpdate) AddUserAddresIDs(ids ...string) *UserUpdate {
	uu.mutation.AddUserAddresIDs(ids...)
	return uu
}

// AddUserAddress adds the "user_address" edges to the UserAddress entity.
func (uu *UserUpdate) AddUserAddress(u ...*UserAddress) *UserUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddUserAddresIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearOrderHistories clears all "order_histories" edges to the OrderHistory entity.
func (uu *UserUpdate) ClearOrderHistories() *UserUpdate {
	uu.mutation.ClearOrderHistories()
	return uu
}

// RemoveOrderHistoryIDs removes the "order_histories" edge to OrderHistory entities by IDs.
func (uu *UserUpdate) RemoveOrderHistoryIDs(ids ...string) *UserUpdate {
	uu.mutation.RemoveOrderHistoryIDs(ids...)
	return uu
}

// RemoveOrderHistories removes "order_histories" edges to OrderHistory entities.
func (uu *UserUpdate) RemoveOrderHistories(o ...*OrderHistory) *UserUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uu.RemoveOrderHistoryIDs(ids...)
}

// ClearUserAddress clears all "user_address" edges to the UserAddress entity.
func (uu *UserUpdate) ClearUserAddress() *UserUpdate {
	uu.mutation.ClearUserAddress()
	return uu
}

// RemoveUserAddresIDs removes the "user_address" edge to UserAddress entities by IDs.
func (uu *UserUpdate) RemoveUserAddresIDs(ids ...string) *UserUpdate {
	uu.mutation.RemoveUserAddresIDs(ids...)
	return uu
}

// RemoveUserAddress removes "user_address" edges to UserAddress entities.
func (uu *UserUpdate) RemoveUserAddress(u ...*UserAddress) *UserUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveUserAddresIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if uu.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if uu.mutation.PasswordCleared() {
		_spec.ClearField(user.FieldPassword, field.TypeString)
	}
	if value, ok := uu.mutation.KrName(); ok {
		_spec.SetField(user.FieldKrName, field.TypeString, value)
	}
	if value, ok := uu.mutation.RegisterAt(); ok {
		_spec.SetField(user.FieldRegisterAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
	}
	if value, ok := uu.mutation.SignUpType(); ok {
		_spec.SetField(user.FieldSignUpType, field.TypeString, value)
	}
	if uu.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrderHistoriesTable,
			Columns: []string{user.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedOrderHistoriesIDs(); len(nodes) > 0 && !uu.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrderHistoriesTable,
			Columns: []string{user.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.OrderHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrderHistoriesTable,
			Columns: []string{user.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserAddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAddressTable,
			Columns: []string{user.UserAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserAddressIDs(); len(nodes) > 0 && !uu.mutation.UserAddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAddressTable,
			Columns: []string{user.UserAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserAddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAddressTable,
			Columns: []string{user.UserAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (uuo *UserUpdateOne) SetEmail(s string) *UserUpdateOne {
	uuo.mutation.SetEmail(s)
	return uuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableEmail(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetEmail(*s)
	}
	return uuo
}

// ClearEmail clears the value of the "email" field.
func (uuo *UserUpdateOne) ClearEmail() *UserUpdateOne {
	uuo.mutation.ClearEmail()
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPassword(*s)
	}
	return uuo
}

// ClearPassword clears the value of the "password" field.
func (uuo *UserUpdateOne) ClearPassword() *UserUpdateOne {
	uuo.mutation.ClearPassword()
	return uuo
}

// SetKrName sets the "kr_name" field.
func (uuo *UserUpdateOne) SetKrName(s string) *UserUpdateOne {
	uuo.mutation.SetKrName(s)
	return uuo
}

// SetNillableKrName sets the "kr_name" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableKrName(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetKrName(*s)
	}
	return uuo
}

// SetRegisterAt sets the "register_at" field.
func (uuo *UserUpdateOne) SetRegisterAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetRegisterAt(t)
	return uuo
}

// SetNillableRegisterAt sets the "register_at" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableRegisterAt(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetRegisterAt(*t)
	}
	return uuo
}

// SetLastLogin sets the "last_login" field.
func (uuo *UserUpdateOne) SetLastLogin(t time.Time) *UserUpdateOne {
	uuo.mutation.SetLastLogin(t)
	return uuo
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableLastLogin(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetLastLogin(*t)
	}
	return uuo
}

// SetSignUpType sets the "sign_up_type" field.
func (uuo *UserUpdateOne) SetSignUpType(s string) *UserUpdateOne {
	uuo.mutation.SetSignUpType(s)
	return uuo
}

// SetNillableSignUpType sets the "sign_up_type" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableSignUpType(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetSignUpType(*s)
	}
	return uuo
}

// AddOrderHistoryIDs adds the "order_histories" edge to the OrderHistory entity by IDs.
func (uuo *UserUpdateOne) AddOrderHistoryIDs(ids ...string) *UserUpdateOne {
	uuo.mutation.AddOrderHistoryIDs(ids...)
	return uuo
}

// AddOrderHistories adds the "order_histories" edges to the OrderHistory entity.
func (uuo *UserUpdateOne) AddOrderHistories(o ...*OrderHistory) *UserUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uuo.AddOrderHistoryIDs(ids...)
}

// AddUserAddresIDs adds the "user_address" edge to the UserAddress entity by IDs.
func (uuo *UserUpdateOne) AddUserAddresIDs(ids ...string) *UserUpdateOne {
	uuo.mutation.AddUserAddresIDs(ids...)
	return uuo
}

// AddUserAddress adds the "user_address" edges to the UserAddress entity.
func (uuo *UserUpdateOne) AddUserAddress(u ...*UserAddress) *UserUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddUserAddresIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearOrderHistories clears all "order_histories" edges to the OrderHistory entity.
func (uuo *UserUpdateOne) ClearOrderHistories() *UserUpdateOne {
	uuo.mutation.ClearOrderHistories()
	return uuo
}

// RemoveOrderHistoryIDs removes the "order_histories" edge to OrderHistory entities by IDs.
func (uuo *UserUpdateOne) RemoveOrderHistoryIDs(ids ...string) *UserUpdateOne {
	uuo.mutation.RemoveOrderHistoryIDs(ids...)
	return uuo
}

// RemoveOrderHistories removes "order_histories" edges to OrderHistory entities.
func (uuo *UserUpdateOne) RemoveOrderHistories(o ...*OrderHistory) *UserUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uuo.RemoveOrderHistoryIDs(ids...)
}

// ClearUserAddress clears all "user_address" edges to the UserAddress entity.
func (uuo *UserUpdateOne) ClearUserAddress() *UserUpdateOne {
	uuo.mutation.ClearUserAddress()
	return uuo
}

// RemoveUserAddresIDs removes the "user_address" edge to UserAddress entities by IDs.
func (uuo *UserUpdateOne) RemoveUserAddresIDs(ids ...string) *UserUpdateOne {
	uuo.mutation.RemoveUserAddresIDs(ids...)
	return uuo
}

// RemoveUserAddress removes "user_address" edges to UserAddress entities.
func (uuo *UserUpdateOne) RemoveUserAddress(u ...*UserAddress) *UserUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveUserAddresIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if uuo.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if uuo.mutation.PasswordCleared() {
		_spec.ClearField(user.FieldPassword, field.TypeString)
	}
	if value, ok := uuo.mutation.KrName(); ok {
		_spec.SetField(user.FieldKrName, field.TypeString, value)
	}
	if value, ok := uuo.mutation.RegisterAt(); ok {
		_spec.SetField(user.FieldRegisterAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.SignUpType(); ok {
		_spec.SetField(user.FieldSignUpType, field.TypeString, value)
	}
	if uuo.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrderHistoriesTable,
			Columns: []string{user.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedOrderHistoriesIDs(); len(nodes) > 0 && !uuo.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrderHistoriesTable,
			Columns: []string{user.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.OrderHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrderHistoriesTable,
			Columns: []string{user.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserAddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAddressTable,
			Columns: []string{user.UserAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserAddressIDs(); len(nodes) > 0 && !uuo.mutation.UserAddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAddressTable,
			Columns: []string{user.UserAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserAddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserAddressTable,
			Columns: []string{user.UserAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
