// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"product-server/ent/orderhistory"
	"product-server/ent/predicate"
	"product-server/ent/user"
	"product-server/ent/useraddress"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAddressQuery is the builder for querying UserAddress entities.
type UserAddressQuery struct {
	config
	ctx                *QueryContext
	order              []useraddress.OrderOption
	inters             []Interceptor
	predicates         []predicate.UserAddress
	withOrderHistories *OrderHistoryQuery
	withUser           *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserAddressQuery builder.
func (uaq *UserAddressQuery) Where(ps ...predicate.UserAddress) *UserAddressQuery {
	uaq.predicates = append(uaq.predicates, ps...)
	return uaq
}

// Limit the number of records to be returned by this query.
func (uaq *UserAddressQuery) Limit(limit int) *UserAddressQuery {
	uaq.ctx.Limit = &limit
	return uaq
}

// Offset to start from.
func (uaq *UserAddressQuery) Offset(offset int) *UserAddressQuery {
	uaq.ctx.Offset = &offset
	return uaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uaq *UserAddressQuery) Unique(unique bool) *UserAddressQuery {
	uaq.ctx.Unique = &unique
	return uaq
}

// Order specifies how the records should be ordered.
func (uaq *UserAddressQuery) Order(o ...useraddress.OrderOption) *UserAddressQuery {
	uaq.order = append(uaq.order, o...)
	return uaq
}

// QueryOrderHistories chains the current query on the "order_histories" edge.
func (uaq *UserAddressQuery) QueryOrderHistories() *OrderHistoryQuery {
	query := (&OrderHistoryClient{config: uaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useraddress.Table, useraddress.FieldID, selector),
			sqlgraph.To(orderhistory.Table, orderhistory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, useraddress.OrderHistoriesTable, useraddress.OrderHistoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(uaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (uaq *UserAddressQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: uaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useraddress.Table, useraddress.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, useraddress.UserTable, useraddress.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserAddress entity from the query.
// Returns a *NotFoundError when no UserAddress was found.
func (uaq *UserAddressQuery) First(ctx context.Context) (*UserAddress, error) {
	nodes, err := uaq.Limit(1).All(setContextOp(ctx, uaq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{useraddress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uaq *UserAddressQuery) FirstX(ctx context.Context) *UserAddress {
	node, err := uaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserAddress ID from the query.
// Returns a *NotFoundError when no UserAddress ID was found.
func (uaq *UserAddressQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = uaq.Limit(1).IDs(setContextOp(ctx, uaq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useraddress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uaq *UserAddressQuery) FirstIDX(ctx context.Context) string {
	id, err := uaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserAddress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserAddress entity is found.
// Returns a *NotFoundError when no UserAddress entities are found.
func (uaq *UserAddressQuery) Only(ctx context.Context) (*UserAddress, error) {
	nodes, err := uaq.Limit(2).All(setContextOp(ctx, uaq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{useraddress.Label}
	default:
		return nil, &NotSingularError{useraddress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uaq *UserAddressQuery) OnlyX(ctx context.Context) *UserAddress {
	node, err := uaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserAddress ID in the query.
// Returns a *NotSingularError when more than one UserAddress ID is found.
// Returns a *NotFoundError when no entities are found.
func (uaq *UserAddressQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = uaq.Limit(2).IDs(setContextOp(ctx, uaq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useraddress.Label}
	default:
		err = &NotSingularError{useraddress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uaq *UserAddressQuery) OnlyIDX(ctx context.Context) string {
	id, err := uaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserAddresses.
func (uaq *UserAddressQuery) All(ctx context.Context) ([]*UserAddress, error) {
	ctx = setContextOp(ctx, uaq.ctx, "All")
	if err := uaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserAddress, *UserAddressQuery]()
	return withInterceptors[[]*UserAddress](ctx, uaq, qr, uaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uaq *UserAddressQuery) AllX(ctx context.Context) []*UserAddress {
	nodes, err := uaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserAddress IDs.
func (uaq *UserAddressQuery) IDs(ctx context.Context) (ids []string, err error) {
	if uaq.ctx.Unique == nil && uaq.path != nil {
		uaq.Unique(true)
	}
	ctx = setContextOp(ctx, uaq.ctx, "IDs")
	if err = uaq.Select(useraddress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uaq *UserAddressQuery) IDsX(ctx context.Context) []string {
	ids, err := uaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uaq *UserAddressQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uaq.ctx, "Count")
	if err := uaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uaq, querierCount[*UserAddressQuery](), uaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uaq *UserAddressQuery) CountX(ctx context.Context) int {
	count, err := uaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uaq *UserAddressQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uaq.ctx, "Exist")
	switch _, err := uaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uaq *UserAddressQuery) ExistX(ctx context.Context) bool {
	exist, err := uaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserAddressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uaq *UserAddressQuery) Clone() *UserAddressQuery {
	if uaq == nil {
		return nil
	}
	return &UserAddressQuery{
		config:             uaq.config,
		ctx:                uaq.ctx.Clone(),
		order:              append([]useraddress.OrderOption{}, uaq.order...),
		inters:             append([]Interceptor{}, uaq.inters...),
		predicates:         append([]predicate.UserAddress{}, uaq.predicates...),
		withOrderHistories: uaq.withOrderHistories.Clone(),
		withUser:           uaq.withUser.Clone(),
		// clone intermediate query.
		sql:  uaq.sql.Clone(),
		path: uaq.path,
	}
}

// WithOrderHistories tells the query-builder to eager-load the nodes that are connected to
// the "order_histories" edge. The optional arguments are used to configure the query builder of the edge.
func (uaq *UserAddressQuery) WithOrderHistories(opts ...func(*OrderHistoryQuery)) *UserAddressQuery {
	query := (&OrderHistoryClient{config: uaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uaq.withOrderHistories = query
	return uaq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uaq *UserAddressQuery) WithUser(opts ...func(*UserQuery)) *UserAddressQuery {
	query := (&UserClient{config: uaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uaq.withUser = query
	return uaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserAddress.Query().
//		GroupBy(useraddress.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uaq *UserAddressQuery) GroupBy(field string, fields ...string) *UserAddressGroupBy {
	uaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserAddressGroupBy{build: uaq}
	grbuild.flds = &uaq.ctx.Fields
	grbuild.label = useraddress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.UserAddress.Query().
//		Select(useraddress.FieldUserID).
//		Scan(ctx, &v)
func (uaq *UserAddressQuery) Select(fields ...string) *UserAddressSelect {
	uaq.ctx.Fields = append(uaq.ctx.Fields, fields...)
	sbuild := &UserAddressSelect{UserAddressQuery: uaq}
	sbuild.label = useraddress.Label
	sbuild.flds, sbuild.scan = &uaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserAddressSelect configured with the given aggregations.
func (uaq *UserAddressQuery) Aggregate(fns ...AggregateFunc) *UserAddressSelect {
	return uaq.Select().Aggregate(fns...)
}

func (uaq *UserAddressQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uaq); err != nil {
				return err
			}
		}
	}
	for _, f := range uaq.ctx.Fields {
		if !useraddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uaq.path != nil {
		prev, err := uaq.path(ctx)
		if err != nil {
			return err
		}
		uaq.sql = prev
	}
	return nil
}

func (uaq *UserAddressQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserAddress, error) {
	var (
		nodes       = []*UserAddress{}
		_spec       = uaq.querySpec()
		loadedTypes = [2]bool{
			uaq.withOrderHistories != nil,
			uaq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserAddress).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserAddress{config: uaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uaq.withOrderHistories; query != nil {
		if err := uaq.loadOrderHistories(ctx, query, nodes,
			func(n *UserAddress) { n.Edges.OrderHistories = []*OrderHistory{} },
			func(n *UserAddress, e *OrderHistory) { n.Edges.OrderHistories = append(n.Edges.OrderHistories, e) }); err != nil {
			return nil, err
		}
	}
	if query := uaq.withUser; query != nil {
		if err := uaq.loadUser(ctx, query, nodes, nil,
			func(n *UserAddress, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uaq *UserAddressQuery) loadOrderHistories(ctx context.Context, query *OrderHistoryQuery, nodes []*UserAddress, init func(*UserAddress), assign func(*UserAddress, *OrderHistory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*UserAddress)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderhistory.FieldAddressID)
	}
	query.Where(predicate.OrderHistory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(useraddress.OrderHistoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AddressID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "address_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (uaq *UserAddressQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserAddress, init func(*UserAddress), assign func(*UserAddress, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*UserAddress)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uaq *UserAddressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uaq.querySpec()
	_spec.Node.Columns = uaq.ctx.Fields
	if len(uaq.ctx.Fields) > 0 {
		_spec.Unique = uaq.ctx.Unique != nil && *uaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uaq.driver, _spec)
}

func (uaq *UserAddressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(useraddress.Table, useraddress.Columns, sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString))
	_spec.From = uaq.sql
	if unique := uaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uaq.path != nil {
		_spec.Unique = true
	}
	if fields := uaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraddress.FieldID)
		for i := range fields {
			if fields[i] != useraddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if uaq.withUser != nil {
			_spec.Node.AddColumnOnce(useraddress.FieldUserID)
		}
	}
	if ps := uaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uaq *UserAddressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uaq.driver.Dialect())
	t1 := builder.Table(useraddress.Table)
	columns := uaq.ctx.Fields
	if len(columns) == 0 {
		columns = useraddress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uaq.sql != nil {
		selector = uaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uaq.ctx.Unique != nil && *uaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uaq.predicates {
		p(selector)
	}
	for _, p := range uaq.order {
		p(selector)
	}
	if offset := uaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserAddressGroupBy is the group-by builder for UserAddress entities.
type UserAddressGroupBy struct {
	selector
	build *UserAddressQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uagb *UserAddressGroupBy) Aggregate(fns ...AggregateFunc) *UserAddressGroupBy {
	uagb.fns = append(uagb.fns, fns...)
	return uagb
}

// Scan applies the selector query and scans the result into the given value.
func (uagb *UserAddressGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uagb.build.ctx, "GroupBy")
	if err := uagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAddressQuery, *UserAddressGroupBy](ctx, uagb.build, uagb, uagb.build.inters, v)
}

func (uagb *UserAddressGroupBy) sqlScan(ctx context.Context, root *UserAddressQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uagb.fns))
	for _, fn := range uagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uagb.flds)+len(uagb.fns))
		for _, f := range *uagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserAddressSelect is the builder for selecting fields of UserAddress entities.
type UserAddressSelect struct {
	*UserAddressQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uas *UserAddressSelect) Aggregate(fns ...AggregateFunc) *UserAddressSelect {
	uas.fns = append(uas.fns, fns...)
	return uas
}

// Scan applies the selector query and scans the result into the given value.
func (uas *UserAddressSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uas.ctx, "Select")
	if err := uas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAddressQuery, *UserAddressSelect](ctx, uas.UserAddressQuery, uas, uas.inters, v)
}

func (uas *UserAddressSelect) sqlScan(ctx context.Context, root *UserAddressQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uas.fns))
	for _, fn := range uas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
