// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"product-server/ent/orderhistory"
	"product-server/ent/predicate"
	"product-server/ent/user"
	"product-server/ent/useraddress"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAddressUpdate is the builder for updating UserAddress entities.
type UserAddressUpdate struct {
	config
	hooks    []Hook
	mutation *UserAddressMutation
}

// Where appends a list predicates to the UserAddressUpdate builder.
func (uau *UserAddressUpdate) Where(ps ...predicate.UserAddress) *UserAddressUpdate {
	uau.mutation.Where(ps...)
	return uau
}

// SetUserID sets the "user_id" field.
func (uau *UserAddressUpdate) SetUserID(s string) *UserAddressUpdate {
	uau.mutation.SetUserID(s)
	return uau
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableUserID(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetUserID(*s)
	}
	return uau
}

// ClearUserID clears the value of the "user_id" field.
func (uau *UserAddressUpdate) ClearUserID() *UserAddressUpdate {
	uau.mutation.ClearUserID()
	return uau
}

// SetKrName sets the "kr_name" field.
func (uau *UserAddressUpdate) SetKrName(s string) *UserAddressUpdate {
	uau.mutation.SetKrName(s)
	return uau
}

// SetNillableKrName sets the "kr_name" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableKrName(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetKrName(*s)
	}
	return uau
}

// SetEnName sets the "en_name" field.
func (uau *UserAddressUpdate) SetEnName(s string) *UserAddressUpdate {
	uau.mutation.SetEnName(s)
	return uau
}

// SetNillableEnName sets the "en_name" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableEnName(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetEnName(*s)
	}
	return uau
}

// SetCustomID sets the "custom_id" field.
func (uau *UserAddressUpdate) SetCustomID(s string) *UserAddressUpdate {
	uau.mutation.SetCustomID(s)
	return uau
}

// SetNillableCustomID sets the "custom_id" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableCustomID(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetCustomID(*s)
	}
	return uau
}

// SetPhone sets the "phone" field.
func (uau *UserAddressUpdate) SetPhone(s string) *UserAddressUpdate {
	uau.mutation.SetPhone(s)
	return uau
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillablePhone(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetPhone(*s)
	}
	return uau
}

// SetKrAddress sets the "kr_address" field.
func (uau *UserAddressUpdate) SetKrAddress(s string) *UserAddressUpdate {
	uau.mutation.SetKrAddress(s)
	return uau
}

// SetNillableKrAddress sets the "kr_address" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableKrAddress(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetKrAddress(*s)
	}
	return uau
}

// SetKrAddressDetail sets the "kr_address_detail" field.
func (uau *UserAddressUpdate) SetKrAddressDetail(s string) *UserAddressUpdate {
	uau.mutation.SetKrAddressDetail(s)
	return uau
}

// SetNillableKrAddressDetail sets the "kr_address_detail" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableKrAddressDetail(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetKrAddressDetail(*s)
	}
	return uau
}

// SetEnAddress sets the "en_address" field.
func (uau *UserAddressUpdate) SetEnAddress(s string) *UserAddressUpdate {
	uau.mutation.SetEnAddress(s)
	return uau
}

// SetNillableEnAddress sets the "en_address" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableEnAddress(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetEnAddress(*s)
	}
	return uau
}

// SetEnAddressDetail sets the "en_address_detail" field.
func (uau *UserAddressUpdate) SetEnAddressDetail(s string) *UserAddressUpdate {
	uau.mutation.SetEnAddressDetail(s)
	return uau
}

// SetNillableEnAddressDetail sets the "en_address_detail" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillableEnAddressDetail(s *string) *UserAddressUpdate {
	if s != nil {
		uau.SetEnAddressDetail(*s)
	}
	return uau
}

// SetPermanent sets the "permanent" field.
func (uau *UserAddressUpdate) SetPermanent(b bool) *UserAddressUpdate {
	uau.mutation.SetPermanent(b)
	return uau
}

// SetNillablePermanent sets the "permanent" field if the given value is not nil.
func (uau *UserAddressUpdate) SetNillablePermanent(b *bool) *UserAddressUpdate {
	if b != nil {
		uau.SetPermanent(*b)
	}
	return uau
}

// AddOrderHistoryIDs adds the "order_histories" edge to the OrderHistory entity by IDs.
func (uau *UserAddressUpdate) AddOrderHistoryIDs(ids ...string) *UserAddressUpdate {
	uau.mutation.AddOrderHistoryIDs(ids...)
	return uau
}

// AddOrderHistories adds the "order_histories" edges to the OrderHistory entity.
func (uau *UserAddressUpdate) AddOrderHistories(o ...*OrderHistory) *UserAddressUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uau.AddOrderHistoryIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (uau *UserAddressUpdate) SetUser(u *User) *UserAddressUpdate {
	return uau.SetUserID(u.ID)
}

// Mutation returns the UserAddressMutation object of the builder.
func (uau *UserAddressUpdate) Mutation() *UserAddressMutation {
	return uau.mutation
}

// ClearOrderHistories clears all "order_histories" edges to the OrderHistory entity.
func (uau *UserAddressUpdate) ClearOrderHistories() *UserAddressUpdate {
	uau.mutation.ClearOrderHistories()
	return uau
}

// RemoveOrderHistoryIDs removes the "order_histories" edge to OrderHistory entities by IDs.
func (uau *UserAddressUpdate) RemoveOrderHistoryIDs(ids ...string) *UserAddressUpdate {
	uau.mutation.RemoveOrderHistoryIDs(ids...)
	return uau
}

// RemoveOrderHistories removes "order_histories" edges to OrderHistory entities.
func (uau *UserAddressUpdate) RemoveOrderHistories(o ...*OrderHistory) *UserAddressUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uau.RemoveOrderHistoryIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (uau *UserAddressUpdate) ClearUser() *UserAddressUpdate {
	uau.mutation.ClearUser()
	return uau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uau *UserAddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uau.sqlSave, uau.mutation, uau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uau *UserAddressUpdate) SaveX(ctx context.Context) int {
	affected, err := uau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uau *UserAddressUpdate) Exec(ctx context.Context) error {
	_, err := uau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uau *UserAddressUpdate) ExecX(ctx context.Context) {
	if err := uau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uau *UserAddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(useraddress.Table, useraddress.Columns, sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString))
	if ps := uau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uau.mutation.KrName(); ok {
		_spec.SetField(useraddress.FieldKrName, field.TypeString, value)
	}
	if value, ok := uau.mutation.EnName(); ok {
		_spec.SetField(useraddress.FieldEnName, field.TypeString, value)
	}
	if value, ok := uau.mutation.CustomID(); ok {
		_spec.SetField(useraddress.FieldCustomID, field.TypeString, value)
	}
	if value, ok := uau.mutation.Phone(); ok {
		_spec.SetField(useraddress.FieldPhone, field.TypeString, value)
	}
	if value, ok := uau.mutation.KrAddress(); ok {
		_spec.SetField(useraddress.FieldKrAddress, field.TypeString, value)
	}
	if value, ok := uau.mutation.KrAddressDetail(); ok {
		_spec.SetField(useraddress.FieldKrAddressDetail, field.TypeString, value)
	}
	if value, ok := uau.mutation.EnAddress(); ok {
		_spec.SetField(useraddress.FieldEnAddress, field.TypeString, value)
	}
	if value, ok := uau.mutation.EnAddressDetail(); ok {
		_spec.SetField(useraddress.FieldEnAddressDetail, field.TypeString, value)
	}
	if value, ok := uau.mutation.Permanent(); ok {
		_spec.SetField(useraddress.FieldPermanent, field.TypeBool, value)
	}
	if uau.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   useraddress.OrderHistoriesTable,
			Columns: []string{useraddress.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uau.mutation.RemovedOrderHistoriesIDs(); len(nodes) > 0 && !uau.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   useraddress.OrderHistoriesTable,
			Columns: []string{useraddress.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uau.mutation.OrderHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   useraddress.OrderHistoriesTable,
			Columns: []string{useraddress.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uau.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraddress.UserTable,
			Columns: []string{useraddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uau.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraddress.UserTable,
			Columns: []string{useraddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uau.mutation.done = true
	return n, nil
}

// UserAddressUpdateOne is the builder for updating a single UserAddress entity.
type UserAddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAddressMutation
}

// SetUserID sets the "user_id" field.
func (uauo *UserAddressUpdateOne) SetUserID(s string) *UserAddressUpdateOne {
	uauo.mutation.SetUserID(s)
	return uauo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableUserID(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetUserID(*s)
	}
	return uauo
}

// ClearUserID clears the value of the "user_id" field.
func (uauo *UserAddressUpdateOne) ClearUserID() *UserAddressUpdateOne {
	uauo.mutation.ClearUserID()
	return uauo
}

// SetKrName sets the "kr_name" field.
func (uauo *UserAddressUpdateOne) SetKrName(s string) *UserAddressUpdateOne {
	uauo.mutation.SetKrName(s)
	return uauo
}

// SetNillableKrName sets the "kr_name" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableKrName(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetKrName(*s)
	}
	return uauo
}

// SetEnName sets the "en_name" field.
func (uauo *UserAddressUpdateOne) SetEnName(s string) *UserAddressUpdateOne {
	uauo.mutation.SetEnName(s)
	return uauo
}

// SetNillableEnName sets the "en_name" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableEnName(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetEnName(*s)
	}
	return uauo
}

// SetCustomID sets the "custom_id" field.
func (uauo *UserAddressUpdateOne) SetCustomID(s string) *UserAddressUpdateOne {
	uauo.mutation.SetCustomID(s)
	return uauo
}

// SetNillableCustomID sets the "custom_id" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableCustomID(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetCustomID(*s)
	}
	return uauo
}

// SetPhone sets the "phone" field.
func (uauo *UserAddressUpdateOne) SetPhone(s string) *UserAddressUpdateOne {
	uauo.mutation.SetPhone(s)
	return uauo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillablePhone(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetPhone(*s)
	}
	return uauo
}

// SetKrAddress sets the "kr_address" field.
func (uauo *UserAddressUpdateOne) SetKrAddress(s string) *UserAddressUpdateOne {
	uauo.mutation.SetKrAddress(s)
	return uauo
}

// SetNillableKrAddress sets the "kr_address" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableKrAddress(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetKrAddress(*s)
	}
	return uauo
}

// SetKrAddressDetail sets the "kr_address_detail" field.
func (uauo *UserAddressUpdateOne) SetKrAddressDetail(s string) *UserAddressUpdateOne {
	uauo.mutation.SetKrAddressDetail(s)
	return uauo
}

// SetNillableKrAddressDetail sets the "kr_address_detail" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableKrAddressDetail(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetKrAddressDetail(*s)
	}
	return uauo
}

// SetEnAddress sets the "en_address" field.
func (uauo *UserAddressUpdateOne) SetEnAddress(s string) *UserAddressUpdateOne {
	uauo.mutation.SetEnAddress(s)
	return uauo
}

// SetNillableEnAddress sets the "en_address" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableEnAddress(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetEnAddress(*s)
	}
	return uauo
}

// SetEnAddressDetail sets the "en_address_detail" field.
func (uauo *UserAddressUpdateOne) SetEnAddressDetail(s string) *UserAddressUpdateOne {
	uauo.mutation.SetEnAddressDetail(s)
	return uauo
}

// SetNillableEnAddressDetail sets the "en_address_detail" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillableEnAddressDetail(s *string) *UserAddressUpdateOne {
	if s != nil {
		uauo.SetEnAddressDetail(*s)
	}
	return uauo
}

// SetPermanent sets the "permanent" field.
func (uauo *UserAddressUpdateOne) SetPermanent(b bool) *UserAddressUpdateOne {
	uauo.mutation.SetPermanent(b)
	return uauo
}

// SetNillablePermanent sets the "permanent" field if the given value is not nil.
func (uauo *UserAddressUpdateOne) SetNillablePermanent(b *bool) *UserAddressUpdateOne {
	if b != nil {
		uauo.SetPermanent(*b)
	}
	return uauo
}

// AddOrderHistoryIDs adds the "order_histories" edge to the OrderHistory entity by IDs.
func (uauo *UserAddressUpdateOne) AddOrderHistoryIDs(ids ...string) *UserAddressUpdateOne {
	uauo.mutation.AddOrderHistoryIDs(ids...)
	return uauo
}

// AddOrderHistories adds the "order_histories" edges to the OrderHistory entity.
func (uauo *UserAddressUpdateOne) AddOrderHistories(o ...*OrderHistory) *UserAddressUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uauo.AddOrderHistoryIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (uauo *UserAddressUpdateOne) SetUser(u *User) *UserAddressUpdateOne {
	return uauo.SetUserID(u.ID)
}

// Mutation returns the UserAddressMutation object of the builder.
func (uauo *UserAddressUpdateOne) Mutation() *UserAddressMutation {
	return uauo.mutation
}

// ClearOrderHistories clears all "order_histories" edges to the OrderHistory entity.
func (uauo *UserAddressUpdateOne) ClearOrderHistories() *UserAddressUpdateOne {
	uauo.mutation.ClearOrderHistories()
	return uauo
}

// RemoveOrderHistoryIDs removes the "order_histories" edge to OrderHistory entities by IDs.
func (uauo *UserAddressUpdateOne) RemoveOrderHistoryIDs(ids ...string) *UserAddressUpdateOne {
	uauo.mutation.RemoveOrderHistoryIDs(ids...)
	return uauo
}

// RemoveOrderHistories removes "order_histories" edges to OrderHistory entities.
func (uauo *UserAddressUpdateOne) RemoveOrderHistories(o ...*OrderHistory) *UserAddressUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uauo.RemoveOrderHistoryIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (uauo *UserAddressUpdateOne) ClearUser() *UserAddressUpdateOne {
	uauo.mutation.ClearUser()
	return uauo
}

// Where appends a list predicates to the UserAddressUpdate builder.
func (uauo *UserAddressUpdateOne) Where(ps ...predicate.UserAddress) *UserAddressUpdateOne {
	uauo.mutation.Where(ps...)
	return uauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uauo *UserAddressUpdateOne) Select(field string, fields ...string) *UserAddressUpdateOne {
	uauo.fields = append([]string{field}, fields...)
	return uauo
}

// Save executes the query and returns the updated UserAddress entity.
func (uauo *UserAddressUpdateOne) Save(ctx context.Context) (*UserAddress, error) {
	return withHooks(ctx, uauo.sqlSave, uauo.mutation, uauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uauo *UserAddressUpdateOne) SaveX(ctx context.Context) *UserAddress {
	node, err := uauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uauo *UserAddressUpdateOne) Exec(ctx context.Context) error {
	_, err := uauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uauo *UserAddressUpdateOne) ExecX(ctx context.Context) {
	if err := uauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uauo *UserAddressUpdateOne) sqlSave(ctx context.Context) (_node *UserAddress, err error) {
	_spec := sqlgraph.NewUpdateSpec(useraddress.Table, useraddress.Columns, sqlgraph.NewFieldSpec(useraddress.FieldID, field.TypeString))
	id, ok := uauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAddress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraddress.FieldID)
		for _, f := range fields {
			if !useraddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uauo.mutation.KrName(); ok {
		_spec.SetField(useraddress.FieldKrName, field.TypeString, value)
	}
	if value, ok := uauo.mutation.EnName(); ok {
		_spec.SetField(useraddress.FieldEnName, field.TypeString, value)
	}
	if value, ok := uauo.mutation.CustomID(); ok {
		_spec.SetField(useraddress.FieldCustomID, field.TypeString, value)
	}
	if value, ok := uauo.mutation.Phone(); ok {
		_spec.SetField(useraddress.FieldPhone, field.TypeString, value)
	}
	if value, ok := uauo.mutation.KrAddress(); ok {
		_spec.SetField(useraddress.FieldKrAddress, field.TypeString, value)
	}
	if value, ok := uauo.mutation.KrAddressDetail(); ok {
		_spec.SetField(useraddress.FieldKrAddressDetail, field.TypeString, value)
	}
	if value, ok := uauo.mutation.EnAddress(); ok {
		_spec.SetField(useraddress.FieldEnAddress, field.TypeString, value)
	}
	if value, ok := uauo.mutation.EnAddressDetail(); ok {
		_spec.SetField(useraddress.FieldEnAddressDetail, field.TypeString, value)
	}
	if value, ok := uauo.mutation.Permanent(); ok {
		_spec.SetField(useraddress.FieldPermanent, field.TypeBool, value)
	}
	if uauo.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   useraddress.OrderHistoriesTable,
			Columns: []string{useraddress.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uauo.mutation.RemovedOrderHistoriesIDs(); len(nodes) > 0 && !uauo.mutation.OrderHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   useraddress.OrderHistoriesTable,
			Columns: []string{useraddress.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uauo.mutation.OrderHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   useraddress.OrderHistoriesTable,
			Columns: []string{useraddress.OrderHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uauo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraddress.UserTable,
			Columns: []string{useraddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uauo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraddress.UserTable,
			Columns: []string{useraddress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAddress{config: uauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uauo.mutation.done = true
	return _node, nil
}
